# Generated by Django 3.1.1 on 2020-10-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
